#+title: My emacs settings
#+auto_tangle: t

* Table of Contents :TOC:TOC:
- [[#basic-setup][Basic setup]]
  - [[#early-init][Early Init]]
  - [[#setup-package-manager][Setup package manager]]
  - [[#auto-tangle-config][Auto-tangle config]]
  - [[#prompts][Prompts]]
  - [[#warnings][Warnings]]
  - [[#emacs-files][Emacs files]]
  - [[#escape-to-quit-prompts][Escape to quit prompts]]
  - [[#benchmark-init][Benchmark init]]
- [[#editor][Editor]]
  - [[#font][Font]]
  - [[#undo-tree][Undo Tree]]
  - [[#vim-keybindings][Vim keybindings]]
  - [[#lines][Lines]]
  - [[#tabs][Tabs]]
  - [[#scroll][Scroll]]
  - [[#whitspaces][Whitspaces]]
  - [[#focus][Focus]]
  - [[#multiple-cursors][Multiple Cursors]]
- [[#visuals][Visuals]]
  - [[#de-clutter][De-clutter]]
  - [[#theme][Theme]]
  - [[#icons][Icons]]
  - [[#modeline][Modeline]]
- [[#ide][IDE]]
  - [[#auto-close-pairs][Auto close pairs]]
  - [[#languages][Languages]]
  - [[#lsp][LSP]]
  - [[#autosuggestion-and-completion][Autosuggestion and Completion]]
  - [[#dap][DAP]]
  - [[#recent-files][Recent files]]
  - [[#zen-mode]["Zen Mode"]]
  - [[#save-emacs-state][Save emacs state]]
  - [[#cursor-position][Cursor position]]
  - [[#search-and-navigation][Search and Navigation]]
  - [[#tab-bar][Tab Bar]]
- [[#window][Window]]
  - [[#winner-mode][Winner Mode]]
- [[#git][Git]]
  - [[#magit][Magit]]
  - [[#diff-highlight][Diff Highlight]]
  - [[#blamer][Blamer]]
- [[#workspaces][Workspaces]]
  - [[#perspective][Perspective]]
- [[#keybindings][Keybindings]]
  - [[#which-key][Which Key]]
- [[#integrated-terminal][Integrated Terminal]]
  - [[#vterm][Vterm]]
- [[#file-manager][File Manager]]
  - [[#dired][Dired]]
  - [[#treemacs][TreeMacs]]
- [[#buffers][Buffers]]
  - [[#file-buffers][File buffers]]
  - [[#minibuffer][Minibuffer]]
- [[#org-mode][Org Mode]]
  - [[#refile][Refile]]
  - [[#habit][Habit]]
  - [[#priority][Priority]]
  - [[#tables][Tables]]
  - [[#todos][TODOs]]
  - [[#visuals-1][Visuals]]
  - [[#org-capture][Org Capture]]
  - [[#org-agenda][Org Agenda]]
  - [[#org-present][Org Present]]
  - [[#org-drill][Org Drill]]
  - [[#org-alert][Org Alert]]
  - [[#org-roam][Org Roam]]
  - [[#org-roam-ui][Org Roam UI]]
  - [[#toc-org][TOC ORG]]
- [[#social][Social]]
  - [[#telegram][Telegram]]
  - [[#matrix][Matrix]]
- [[#news][News]]
  - [[#rss][RSS]]
- [[#pdf][PDF]]
  - [[#pdf-tools][pdf-tools]]

* Basic setup

** Early Init

#+begin_src emacs-lisp :tangle ~/Git/dotfiles/.emacs.d/early-init.el
#+end_src

#+property: header-args:emacs-lisp :tangle ~/Git/dotfiles/.emacs.d/init.el

** Setup package manager

For many of the following settings I'll need to install some packages, so its best to have it configured upfront.

Note: if you get 404 when trying to install packages, run ~M-x package-refresh-contents~.

*** Setup MELPA

#+begin_src emacs-lisp
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
  (package-initialize)
#+end_src

*** Setup use-package

Install use-package if not installed, then require it.

#+begin_src emacs-lisp
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
  (eval-when-compile (require 'use-package))
#+end_src

This ensures all packages from ~use-package~ are installed when emacs loads.

#+begin_src emacs-lisp
  (setq use-package-always-ensure t)
#+end_src

** Auto-tangle config

#+begin_src emacs-lisp
  (use-package org-auto-tangle
    :defer
    :hook (org-mode . org-auto-tangle-mode))
#+end_src

** Prompts

*** Y or N instead of Yes or No

#+begin_src emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+end_src

** TODO Warnings

Disable annoying warnings at startup.

TODO: check all available levels

#+begin_src emacs-lisp
  (setq warning-minimum-level :emergency)
#+end_src

** Emacs files

Emacs creates a bunch of annoying files.

*** Disable lock files

#+begin_src emacs-lisp
  (setq create-lockfiles nil)
#+end_src

*** Emacs directories

#+begin_src emacs-lisp
  (setq user-emacs-directory "~/.cache/emacs/")
  (when (not (file-directory-p user-emacs-directory))
    (make-directory user-emacs-directory))

  ;; wtf
  (setq backup-directory-alist
	`((".*" . ,(expand-file-name "backups" user-emacs-directory)))
				     backup-by-copying t
				     version-control t
				     delete-old-versions t
				     vc-make-backup-files t
				     kept-old-versions 10
				     kept-new-versions 10)

#+end_src

*** Custom variables file

This way I can build init.el from init.org without loosing custom variables.

#+begin_src emacs-lisp
  (setq custom-file "~/Git/dotfiles/.emacs.d/custom.el")
#+end_src

** Escape to quit prompts

Press escape to quit most prompts.

#+begin_src emacs-lisp
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+end_src

** Benchmark init

I was getting very bad startup times so I added this just to be sure.

#+begin_src emacs-lisp
  (use-package esup
    :defer
    :config
    (setq esup-depth 0))
#+end_src

* Editor

Basic editor settings. For more advanced tools see [[#ide][IDE]].

** Font

Increase default font size

#+begin_src emacs-lisp
  (set-face-attribute 'default nil :height 140)
  (when (eq system-type 'darwin)
    (set-face-attribute 'default nil :height 160))
#+end_src

** Undo Tree

~C-x u~ launches the undo tree visualization.

#+begin_src emacs-lisp
  (use-package undo-tree
    :demand t
    :config
    (when (not (file-directory-p "~/.emacs.d/undotree"))
      (make-directory "~/.emacs.d/undotree"))
    (setq undo-tree-history-directory-alist '(("." . "~/.emacs.d/undotree")))
    (setq evil-undo-system 'undo-tree)
    (global-undo-tree-mode 1))
#+end_src

** Vim keybindings

*** Evil Mode

evil mode and evil-collection provide vim-like bindings.

#+begin_src emacs-lisp
  (use-package evil
    :demand t
    :custom
    (evil-want-integration t)
    (evil-want-C-u-scroll t) ; C-u won't be enabled by default
    (evil-want-keybinding nil) ; what? idk
    (evil-want-minibuffer t)
    (evil-undo-system 'undo-tree)
    :bind
    (:map evil-normal-state-map
          ("SPC u" . universal-argument))
    :config
    (evil-set-leader 'normal (kbd "SPC"))
    (evil-mode 1))

  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))
#+end_src


*** Keychord

I only use it to map ~jk~ to ~<Escape>~.

#+begin_src emacs-lisp
  (use-package key-chord
    :after evil
    :config
    (key-chord-mode 1)
    (setq key-chord-two-keys-delay 0.2)
    (key-chord-define evil-insert-state-map "jk" 'evil-normal-state))
#+end_src

** Lines

Show column number.

#+begin_src emacs-lisp
  (column-number-mode 1) ;; TODO
#+end_src

Absolute line numbers for insert state and relative for others.

#+begin_src emacs-lisp
  (use-package emacs
	:hook ((evil-insert-state-entry
			. (lambda ()
				(setq display-line-numbers-type t)
				(display-line-numbers-mode 1)))
		   (evil-insert-state-exit
			. (lambda ()
				(setq display-line-numbers-type 'relative)
				(display-line-numbers-mode 1)))))
#+end_src

Enable line numbers for some modes.

#+begin_src emacs-lisp
  (dolist (mode '(text-mode-hook
                 prog-mode-hook
                 conf-mode-hook))
    (add-hook mode #'display-line-numbers-mode))
#+end_src

Wrap long lines.

#+begin_src emacs-lisp
  ;;(global-visual-line-mode 1)
#+end_src

Truncate long lines.

#+begin_src emacs-lisp
  (set-default 'truncate-lines t)
#+end_src

Automatically break line wider than 80 cols.

#+begin_src emacs-lisp
  (setq-default fill-column 80)
#+end_src

** Tabs

#+begin_src emacs-lisp
  (setq-default tab-width 4)
#+end_src

Indent wrapped lines.

#+begin_src emacs-lisp
  ;;(add-hook 'visual-line-mode 'adaptive-wrap-prefix-mode)
#+end_src

** Scroll

I don't know how to explain this shit.
But it improves scrolling for sure.

TODO: check what each settings do.

#+begin_src emacs-lisp
  ;; (setq scroll-step 1)
  ;; (setq scroll-margin 1)
  ;; (setq scroll-conservatively 1000)
  ;; (setq scroll-preserve-screen-position 1)
#+end_src

** TODO Whitspaces

*** TODO Highlight trailing whitespaces

TODO: add other modes

#+begin_src emacs-lisp
  (add-hook 'prog-mode '(setq show-trailing-whitespace t))
#+end_src

*** TODO Show symbols for spaces and tabs
TODO: show a symbol like ~>~ for tab and ~•~, ideally in visual mode.

** Focus

Makes only the current area highlighted.

#+begin_src emacs-lisp
  (use-package focus :defer)
#+end_src

** TODO Multiple Cursors

#+begin_src emacs-lisp
  (use-package evil-mc :defer)
#+end_src

* Visuals

** De-clutter

Hides startup message, scroll bar and tool bar.
#+begin_src emacs-lisp
  (setq inhibit-startup-message t)
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (menu-bar-mode -1)
#+end_src

No annoying bell sound nor flashing lights when something goes wrong.
#+begin_src emacs-lisp
  (blink-cursor-mode 0)
  (setq ring-bell-function 'ignore) ; this is actually sound, but...
#+end_src

Launch in fullscreen.
#+begin_src emacs-lisp
  (toggle-frame-fullscreen)
#+end_src

** Theme

*** Doom Themes

#+begin_src emacs-lisp
  (use-package doom-themes
    :defer 0.3
    :config
    (setq doom-themes-enable-bold t)
    (setq doom-themes-enable-italic t)
    (load-theme 'doom-one t))
#+end_src

** Icons

#+begin_src emacs-lisp
  (use-package all-the-icons
    :if (display-graphic-p))

  (use-package all-the-icons-dired
    :hook (dired-mode . all-the-icons-dired-mode))

  ;; run once
  ;;(all-the-icons-install-fonts t)
  ;;(nerd-icons-install-fonts t)
#+end_src

** Modeline

*** Doom Modeline
Nicer modeline.

#+begin_src emacs-lisp
  (use-package doom-modeline
    :defer 1
    :config (doom-modeline-mode 1))
#+end_src

* IDE

** Auto close pairs

Auto close pairs like '',"", [ ], { }, depending on the file type.

#+begin_src emacs-lisp
  (electric-pair-mode 1)
#+end_src

** Languages
*** Go

#+begin_src emacs-lisp
  (use-package go-mode
    :defer
    :hook
    (go-mode . eglot-ensure))
#+end_src

Tool for adding/removing struct tags.

#+begin_src emacs-lisp
  (use-package go-tag :defer)
#+end_src

*** Nix
#+begin_src emacs-lisp
  (use-package nix-mode :defer)
#+end_src

*** YAML
#+begin_src emacs-lisp
  (use-package yaml-mode :defer)
#+end_src

*** Markdown
#+begin_src emacs-lisp
  (use-package markdown-mode :defer)
#+end_src

** LSP

*** Eglot

Eglot is a builtin LSP client for emacs.

#+begin_src emacs-lisp
  (use-package eglot
    :hook
    (before-save . eglot-format)

    :bind
    (:map evil-normal-state-map
          ("gi" . eglot-find-implementation)
          ("SPC l r" . eglot-rename)
          ("SPC l R" . eglot-reconnect)
          ("SPC l a a" . eglot-code-actions)
          ("SPC l a e" . eglot-code-action-extract))
    :init
    (setq eglot-sync-connect nil) ;; do not block when loading lsp


    ;; TODO
    (add-hook 'before-save-hook
              (lambda ()
                (call-interactively 'eglot-code-action-organize-imports))
              t nil))
#+end_src

*** Eldoc and Eldoc box

Show docs as a hover box instead of using echo area.

#+begin_src emacs-lisp
  (use-package eldoc-box
      :config
      (eldoc-box-hover-at-point-mode 1)
      (setq eldoc-echo-area-use-multiline-p 1)
      (advice-add 'eldoc-doc-buffer :override 'eldoc-box-help-at-point))
#+end_src

** Autosuggestion and Completion

Emacs supports completion builtin with ~C-M-i~, but for a VSCode-like completion I use corfu.
You can still use ~C-M-i~ to launch corfu.

#+begin_src emacs-lisp
  (use-package corfu
    :config
    (setq corfu-auto t)
    (setq corfu-auto-delay 0.2)
    (setq corfu-auto-prefix 1)
    (setq corfu-cycle t)
    (global-set-key (kbd "C-SPC") #'completion-at-point)
    (global-corfu-mode 1))
#+end_src

** TODO DAP

#+begin_src emacs-lisp
  (use-package dap-mode)
#+end_src

** Recent files

Show recent files with ~C-x C-r~.

#+begin_src emacs-lisp
  (recentf-mode 1)
  (setq recentf-max-menu-items 100)
  (setq recentf-max-saved-items 100)
  (global-set-key "\C-x\ \C-r" 'recentf-open)
#+end_src

** "Zen Mode"

#+begin_src emacs-lisp
  (use-package visual-fill-column
    :init
    (setq visual-fill-column-center-text t)
    (setq visual-fill-column-width 110)
    :config
    (global-visual-fill-column-mode 1))
#+end_src

** Save emacs state

Save session when emacs is closed and restore when reopened.

#+begin_src emacs-lisp
  ;;(desktop-save-mode 1)
#+end_src

** Cursor position

Save cursor position per file.

#+begin_src emacs-lisp
  (save-place-mode 1)
#+end_src

** Search and Navigation

#+begin_src emacs-lisp
  (use-package consult
    :defer
    :bind
    (:map evil-normal-state-map
          ("SPC g s" . consult-grep)))
#+end_src

** Tab Bar

#+begin_src emacs-lisp
  (use-package emacs
    :config
    (setq tab-bar-tab-hints t)
    :bind
    (:map evil-normal-state-map
          ("gc" . tab-bar-close-tab)
          ("gn" . tab-bar-new-tab)
          ("gh" . tab-bar-switch-to-prev-tab)
          ("gl" . tab-bar-switch-to-next-tab)))
#+end_src

* Window

** Winner Mode

Winner Mode can undo and redo window changes, like opening and closing.

#+begin_src emacs-lisp
  (use-package emacs
    :bind
    (:map evil-normal-state-map
          ("C-w u" . winner-undo)
          ("C-w C-r" . winner-redo))
    :config
    (winner-mode 1))
#+end_src


* Git

** Magit

I use the default ~C-x g~ binding.

TODO: hook to file save

#+begin_src emacs-lisp
  (use-package magit :defer)
#+end_src

** Diff Highlight

TODO: hook to magit

#+begin_src emacs-lisp
  (use-package diff-hl
    :defer 1
    :hook ((magit-pre-refresh . diff-hl-magit-pre-refresh)
           (magit-post-refresh . diff-hl-magit-post-refresh))
    :init (global-diff-hl-mode 1))
#+end_src

** Blamer

Blamer shows a git blame similar to GitLens in VSCode.

#+begin_src emacs-lisp
  (use-package blamer :defer)
#+end_src

* Workspaces

** Perspective

#+begin_src emacs-lisp
  (use-package perspective
    :bind
    (:map evil-normal-state-map
          ("SPC SPC p" . persp-mode)
          ("SPC SPC s" . persp-switch)
          ("SPC SPC l" . persp-next)
          ("SPC SPC h" . persp-prev)))
#+end_src

* Keybindings

** Which Key

~whick-key~ suggests key combinations as you press them.

#+begin_src emacs-lisp
  (use-package which-key
    :config
    (setq which-key-idle-delay 0.5)
    (which-key-mode))
#+end_src

* Integrated Terminal

** Vterm

#+begin_src emacs-lisp
  (use-package vterm
    :ensure nil
    :defer
    :init
    (define-key evil-normal-state-map (kbd "SPC t") 'vterm))
#+end_src

* File Manager
** Dired

Automatically update dired when a file is changed.

#+begin_src emacs-lisp
  (setq global-auto-revert-non-file-buffers t)
#+end_src

** TreeMacs

File tree on the left side.

#+begin_src emacs-lisp
  (use-package treemacs
    :config
    (setq treemacs-width 40)
    :bind
    (:map global-map
	  ([f8] . treemacs)))
#+end_src

* Buffers

** File buffers
Refreshs file automatically when its changed by other program. Also refreshes dired.

#+begin_src emacs-lisp
  (use-package emacs
    :bind
    (:map evil-normal-state-map
          (("gb" . evil-switch-to-windows-last-buffer)))
    :config
    (global-auto-revert-mode 1))

#+end_src

** Minibuffer

*** Persist minibuffers

Persist minibuffers history, like in ~M-x~, ~C-x C-f~ and so on.

#+begin_src emacs-lisp
  (savehist-mode 1)
  (setq history-length 100)
#+end_src

*** Vertico

Improves minibuffer by showing multiple options in a vertical list.

#+begin_src emacs-lisp
  (use-package vertico
    :config
    (vertico-mode 1)
    (setq vertico-count 20)
    (setq vertico-cycle t)
    (keymap-set vertico-map "C-j" #'vertico-next)
    (keymap-set vertico-map "C-k" #'vertico-previous))
#+end_src

Make vertico appear at the center of the screen.

#+begin_src emacs-lisp
  (use-package vertico-posframe
    :config (vertico-posframe-mode))
#+end_src

*** Marginalia

- Adds description for commands in ~M-x~
- Adds extra info to find file
- Adds extra info to ~C-h v~

#+begin_src emacs-lisp
  (use-package marginalia
    :init
    (marginalia-mode))
#+end_src

*** Orderless

Provides fuzzy search for files, commands, variables, and so on.

#+begin_src emacs-lisp
  (use-package orderless
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src

* Org Mode

** Refile

#+begin_src emacs-lisp
  (use-package org
    :config
    (setq org-directory "~/Org"))

  ;; (advice-add 'org-refile :after 'org-save-all-org-buffers)
#+end_src

** Habit

#+begin_src emacs-lisp
  (use-package org
    :config
    (require 'org-habit)
    (add-to-list 'org-modules 'org-habit)
    (setq org-habit-graph-column 60))
#+end_src


** Priority

#+begin_src emacs-lisp
  (use-package org
    :config
    (setq org-priority-highest 0)
    (setq org-priority-lowest 5)
    (setq org-priority-default 5))
#+end_src

** Tables

#+begin_src emacs-lisp
  (use-package org
    :bind
    (:map org-mode-map
          ("C-c h" . org-table-move-cell-left)
          ("C-c l" . org-table-move-cell-right)
          ("C-c k" . org-table-move-cell-up)
          ("C-c j" . org-table-move-cell-down)))
#+end_src

** TODOs

#+begin_src emacs-lisp
  (use-package org
    :config
    (setq org-log-done 'item)
    (setq org-hierarchical-todo-statistics nil) ;; TODO recursive by default
    (setq org-todo-keywords
          '((sequence "TODO" "|" "DONE"))))
#+end_src

** Visuals

Show headings with special bullets instead o asterisks.

#+begin_src emacs-lisp
  (use-package org-bullets
    :hook (org-mode . org-bullets-mode))
#+end_src

Visually indent text inside headings.

#+begin_src emacs-lisp
  (use-package org
    :hook (org-mode . org-indent-mode))
#+end_src

Change title and heading sizes.

#+begin_src emacs-lisp
  (defvar my/org-big-fonts '((org-document-title . 1.8)
                             (org-level-1 . 1.6)
                             (org-level-2 . 1.4)
                             (org-level-3 . 1.2)))
  (defun my/org-big ()
    (interactive)
    (dolist (face my/org-big-fonts)
      (set-face-attribute (car face) nil :height (cdr face))))

  (defun my/org-smol ()
    (interactive)
    (dolist (face my/org-big-fonts)
      (set-face-attribute (car face) nil :height 1.0)))
#+end_src

Whether to hide or not symbols for emphasis like ~a~, *b*, /c/...

#+begin_src emacs-lisp
 (setq org-hide-emphasis-markers t)
#+end_src

Replace ~-~ by ~•~ on unordered lists.

#+begin_src emacs-lisp
  (font-lock-add-keywords 'org-mode
      '(("^ *\\([-]\\) "
      (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
#+end_src

** Org Capture

#+begin_src emacs-lisp
  (use-package org
    :bind
    (:map global-map
          ("C-c c" . org-capture))
    :config
    (setq org-capture-templates
          '(("t"
             "todo item"
             entry
             (file+headline org-default-notes-file "Tasks")
             "* TODO %?\n"))))
#+end_src

** Org Agenda

#+begin_src emacs-lisp
  (use-package org
	:init
	(setq org-agenda-files
		  '("Roam/20240620102058-tasks.org"))
	;; default:
	;; (setq org-agenda-prefix-format
	;; 		'((agenda . " %i %-12:c%?-12t% s")
	;; 		 (todo . " %i %-12:c")
	;; 		 (tags . " %i %-12:c")
	;; 		 (search . " %i %-12:c")))
	(setq org-agenda-prefix-format
		  '((agenda . " %?-12t% s")
			(todo . " ")
			(tags . " ")
			(search . " ")))
	:bind
	(:map global-map
		  ("C-c a" . org-agenda)))
#+end_src

** Org Present

#+begin_src emacs-lisp
  (use-package org-present
    :defer
    :hook ((org-present-mode
            . (lambda ()
                (org-present-hide-cursor)
				(setq display-line-numbers-type nil)
                (display-line-numbers-mode 1)))
           (org-present-mode-quit
            . (lambda ()
                (org-present-show-cursor)
				(setq display-line-numbers-type 'relative)
                (display-line-numbers-mode 1)))))
#+end_src

** Org Drill

#+begin_src emacs-lisp
  (use-package org-drill
    :config
    (add-to-list 'org-modules 'org-drill))
#+end_src

** Org Alert

#+begin_src emacs-lisp
  (use-package org-alert
    :config
    (when (eq system-type 'darwin)
      (setq alert-default-style 'osx-notifier))
    (setq org-alert-interval 60)
    (setq org-alert-notify-cutoff 10)
    (setq org-alert-notify-after-event-cutoff 2)
    (org-alert-enable))
#+end_src

** Org Roam

#+begin_src emacs-lisp
  (use-package org-roam
    :defer
    :config
    (when (not (file-directory-p "~/Org/Roam"))
      (make-directory "~/Org/Roam"))
    (setq org-roam-directory "~/Org/Roam")

    (org-roam-db-autosync-enable)

    :bind
    (("C-c n f" . org-roam-node-find)
     ("C-c n i" . org-roam-node-insert)
     ("C-c n d d" . org-roam-dailies-goto-today)
     ("C-c n d y" . org-roam-dailies-goto-yesterday)
     ("C-c n d t" . org-roam-dailies-goto-tomorrow)))
#+end_src

** Org Roam UI

Visualize Roam graph in real time.

#+begin_src emacs-lisp
  (use-package org-roam-ui :defer)
#+end_src

** TOC ORG

Generate a table-of-contents automatically.

#+begin_src emacs-lisp
  (use-package toc-org
    :hook
    (org-mode . toc-org-mode))
#+end_src

* Social

** Telegram

#+begin_src emacs-lisp
  (use-package telega
    :ensure nil ;; installed and built through nix
    :init
    (setq telega-emoji-use-images nil))
#+end_src

** Matrix

#+begin_src emacs-lisp
  (use-package ement :defer)
#+end_src

* News

** RSS

#+begin_src emacs-lisp
  (use-package elfeed
    :config
    (setq elfeed-feeds
          '(
            ;; DHH
            "https://world.hey.com/dhh/feed.atom" 
            ;; Martin Fowler
            "https://martinfowler.com/feed.atom" 
            ;; Go Blog
            "https://go.dev/blog/feed.atom" 
            ;; ThePrimeTime
            "https://www.youtube.com/feeds/videos.xml?channel_id=UCUyeluBRhGPCW4rPe_UvBZQ" 
            ;; Mental Outlaw
            "https://www.youtube.com/feeds/videos.xml?channel_id=UC7YOGHUfC1Tb6E4pudI9STA" 
            ;; Fireship
            "https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA" 
            ;; Lakka News
            "https://www.lakka.tv/articles/feed.xml" 
            )))
#+end_src

*** TODO org-elfeed

* PDF

** pdf-tools

I tried default emacs doc-view-mode but it didn't work with the PDFs I tested.

Installing pdf-tools and opening a PDF file just works here.

#+begin_src emacs-lisp
  (use-package pdf-tools
    :config
    (pdf-tools-install))
#+end_src
