#+title: My emacs settings
#+property: header-args:emacs-lisp :tangle ./init.el

** Visuals

*** De-clutter

Hides startup message, scroll bar and tool bar.
#+begin_src emacs-lisp
(setq inhibit-startup-message t)
(scroll-bar-mode -1)
(tool-bar-mode -1)
#+end_src

No annoying bell sound nor flashing lights when something goes wrong.
#+begin_src emacs-lisp
(blink-cursor-mode 0)
(setq ring-bell-function 'ignore) ; this is actually sound, but...
#+end_src


*** Lines

Show relative line numbers.
#+begin_src emacs-lisp
(global-display-line-numbers-mode 1)
(setq display-line-numbers 'relative)
#+end_src


#+begin_src emacs-lisp
#+end_src

Wrap long lines.
#+begin_src emacs-lisp
(visual-line-mode 1)
#+end_src

*** Scroll

I don't know how to explain this shit.
But it improves scrolling for sure.

#+begin_src emacs-lisp
(setq scroll-step 1)
(setq scroll-margin 10)
(setq scroll-conservatively 1000)
(setq scroll-preserve-screen-position 1)
#+end_src

*** Font and Theme

I just use the default font with a bigger size.
#+begin_src emacs-lisp
(set-face-attribute 'default nil :height 140)
#+end_src

Global theme.
#+begin_src emacs-lisp
; looks like vscode light theme
(load-theme 'leuven)

; usable dark theme
;(load-theme 'modus-vivendi)
#+end_src

*** Whitspaces

Colors trailing whitespaces in red.
**** TODO only use for code. Its currently being applied to terminal too.
#+begin_src emacs-lisp
(setq-default show-trailing-whitespace t)
#+end_src

**** TODO show symbols for spaces and tabs

** Behavior

Make emacs behave more like an IDE.

*** Persist minibuffers

Persist minibuffers history, like in ~M-x~, ~C-x C-f~ and so on.

#+begin_src emacs-lisp
(savehist-mode 1)
(setq history-length 25)
#+end_src

*** Auto close pairs

Auto close pairs like ~''~, ~""~, ~[ ]~, ~{ }~, depending on the file type.

#+begin_src emacs-lisp
(electric-pair-mode 1)
#+end_src

*** Recent opened files

Show recent files with ~M-x recentf~.

#+begin_src emacs-lisp
(recentf-mode 1)
#+end_src

*** Save session

Save session when emacs is closed and restore when reopened.

#+begin_src emacs-lisp
(desktop-save-mode 1)
#+end_src

*** Cursor position

Save cursor position per file.

#+begin_src emacs-lisp
(save-place-mode 1)
#+end_src

*** Auto refresh files

Refreshs file automatically when its changed by other program. Also refreshes dired.

#+begin_src emacs-lisp
(global-auto-revert-mode 1)
(setq global-auto-revert-non-file-buffers t) ; for dired
#+end_src

*** Escape to quit prompts

Press escape to quit most prompts.

#+begin_src emacs-lisp
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+end_src

** Org Mode

#+begin_src emacs-lisp
; org mode lists
; (font-lock-add-keywords 'org-mode
;     '(("^ *\\([-]\\) "
;     (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

(add-hook 'org-mode-hook #'(lambda()
			    ;(org-bullets-mode 1)
			    (set-face-attribute 'org-document-title nil :height 1.8)
			    (set-face-attribute 'org-level-1 nil :height 1.8)
			    (set-face-attribute 'org-level-2 nil :height 1.5)
			    (set-face-attribute 'org-level-3 nil :height 1.2)))
#+end_src

** Packages

#+begin_src emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(setq use-package-always-ensure t)

; install use-package
(unless (package-installed-p 'use-package)
(package-refresh-contents)
(package-install 'use-package))
(eval-when-compile (require 'use-package))

(use-package key-chord
:config
(key-chord-mode 1))

; vim-like bindings
(use-package evil
:after key-chord
:demand t
:init
(setq evil-want-C-u-scroll t)
(setq evil-want-keybinding nil)
:config
(setq key-chord-two-keys-delay 0.2)
(key-chord-define evil-insert-state-map "jk" 'evil-normal-state)
(evil-mode 1))

(use-package evil-collection
:after evil
:config
(setq evil-want-integration t)
(evil-collection-init))

; lsp builtin client
(use-package eglot
:hook
(go-mode . eglot-ensure)
:config
(keymap-set eglot-mode-map "C-x r" #'eglot-rename))

; format on save
(add-hook 'before-save-hook 'eglot-format)

; autosuggestions
(use-package corfu
:custom
(corfu-auto t)
:init
(global-corfu-mode))

; languages
(use-package go-mode)

(use-package nix-mode)

(use-package which-key
:config (which-key-mode))

(use-package vertico
:config
(vertico-mode 1)
(keymap-set vertico-map "C-j" #'vertico-next)
(keymap-set vertico-map "C-k" #'vertico-previous))

(use-package magit)

(use-package neotree
:config
(global-set-key [f8] 'neotree-toggle))

(use-package restart-emacs)

; --- ignore below ---
(custom-set-variables
;; custom-set-variables was added by Custom.
;; If you edit it by hand, you could mess it up, so be careful.
;; Your init file should contain only one such instance.
;; If there is more than one, they won't work right.
'(package-selected-packages
    '(org-bullets restart-emacs neotree magit corfu nix-mode vertico which-key use-package lsp-mode key-chord ivy go-mode evil-collection command-log-mode)))
(custom-set-faces
;; custom-set-faces was added by Custom.
;; If you edit it by hand, you could mess it up, so be careful.
;; Your init file should contain only one such instance.
;; If there is more than one, they won't work right.
)
#+end_src
